#!/usr/bin/env bash

function main {
  set -x

  if [[ ! -f /etc/ssh/ssh_host_rsa_key ]]; then
    rm -fv /etc/ssh/ssh_host_*
    dpkg-reconfigure openssh-server
    #chown -R app:app /etc/ssh /run
  fi

  #echo LOGLEVEL DEBUG3 | sudo tee -a /etc/ssh/sshd_config

  exec /usr/sbin/sshd -D -o UseDNS=no -o UsePAM=yes -o PasswordAuthentication=no -o Port=22 -e
}

main "$@"
