ARG IMAGE

FROM $IMAGE

RUN pwd
RUN find .asdf -ls
RUN pwd

RUN ./run .asdf/bin/asdf plugin-add terraform

COPY --chown=app:app etc/tool-versions.terraform .tool-versions

RUN ./run .asdf/bin/asdf install
