apiVersion: v1
kind: Service
metadata:
  name: hanbaiki-dev
  labels:
    app: hanbaiki-dev
spec:
  ports:
    - name: hanbaiki-dev
      port: 2222
      protocol: TCP
      targetPort: hanbaiki-dev
  selector:
    app: hanbaiki-dev
  type: LoadBalancer